apiVersion: v1
kind: Secret
metadata:
  name: volsync-restic-secret
type: Opaque
stringData:
  SECRET_VOLSYNC_S3_ENDPOINT: ENC[AES256_GCM,data:MLC0Kke6Hi9frm8IR0NjWq3kbv00u72IgEd63HX0gQ==,iv:f3xdUegnSbon+I3dwGAXaxgQFKbQJQf33KoVDRspCzw=,tag:GPpl+h05BjpYmA9yde6nEg==,type:str]
  SECRET_VOLSYNC_S3_BUCKET: ENC[AES256_GCM,data:ImaiwEFV7JQoOfbldDazqq8UYUqPRV3CkMD8UxTQpDN1ZAX5qA==,iv:cad2EDuf6t+JD8tyvT/qFgZsiMHaj3hOYDLIgMjSLSw=,tag:reyCxcPInZ62E4M0h+gQsQ==,type:str]
  SECRET_VOLSYNC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:0sbLwojV6ylqZ7sexY5DxjKv+pGU8S770w==,iv:/PhWANqEXMRGfda2t835dnJeW1w9+hKgz0SY4FWcx3A=,tag:mqPgmcdFnYfEYQhXA3L5yQ==,type:str]
  SECRET_VOLSYNC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8BegJ6/r8lhuA+pMWGrHnpwjyqOQ4OrFP25gDlhWYLwMi7f6asW+MA==,iv:TtvoJ7vymkl4LKirqzBC+7Qr7JMMilrLDSOwTuP2Isc=,tag:cDxGzY+auUk33HwM72AzZw==,type:str]
  SECRET_VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:vHmlz3Hm/87N7nRuKnBTs+vPoGWCuyXvqDaV+LC926B50D8HTp2tkaOB0dI2jzrJi4Z3h8o9U/FvNzleEMTdAQ==,iv:O7pC3FbWC3rfSzkO1xw108YDaZ4Y69NyHZcMvsLUQuU=,tag:e0y1OmkDsCUkdkyFic1TXQ==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQ0FRRXg5U1BZVzFwdTRF
        bWVJVFRlYXgwem9LWi9uYWNTVDJMT3B2UFNzCk9ENE5BVzRldC84ZGkwU0lSbVVD
        NDY1d2dRbDFYbExvQUlqbVpOMkJrRTQKLS0tIG5SZUY2T3RmaVFhOUFTRTRtUkND
        TUtvajU0bndNblBGdVFORVNtcG4zNTAKRSvNSL+pKnSn0Yak1aJ4FBxKRbwMuDoK
        I30ZgVbt9UsYeC7p41Mw06zdltM4uFugj9k7b/bHNep/gCQarVcEVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T11:57:51Z"
  mac: ENC[AES256_GCM,data:bKcwj2GFOI5wkdITdaEgMeu1iMmYGLbBaZjdYoZq1nOVjT6cf+QDCmHKqGXPb+qtey00MWUzvp8YRnunDra+kXFnz6/QSXKie0LGNMaFLPvZ9vJm7xY8HB/+oV+gBI8C3t4KDzi+U72N7AdS/ku0mA619d6mA8KAg7swS8nf/Tc=,iv:pquCtq70J+KlFUi66tycgPGwbzj+8KP1tg2WmSdxFUE=,tag:xxFE8YcxsSnsbFEzlFXKBA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
