apiVersion: v1
kind: Secret
metadata:
  name: github-backup-token
type: Opaque
stringData:
  GITHUB_TOKEN: ENC[AES256_GCM,data:taIColB03uF6wh1MseBxOb4ionyrzELOM6Oo6tIcZo47VVzu1AQM68j3UdEgSBX5vX0mSczJK78SXpZwiIyhkXsb5gdx/m6sD3QVG4KkvBtcNzx+md4h/jTR5Skp,iv:T6rsj4S2l4b3AefnIdwhegBS9+RLKkP2rX6nPlbWws0=,tag:LCV65ZtopVfZwHbkY+b8LQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3STZGZUpEdUJNaU4yZ0xV
        TXh1TkNpZXdRM1psSVpML2c1WU16NU1EalRjCk9XOVRnc3lkL2o1V0h0MUoyQTNo
        OHphYjZlL1lJWTNnM001bUxYVi9aa00KLS0tIERJb2FQTk5wRUgwK2ZYWFd2SGg5
        NEZqUGpvOG9XT29mbXBhMnJ1blVkVncKG4PVq0+nVBi3RfVIcbqzITy49S5BrnKJ
        s9nKdwGa54KBAo3/6mUZM8onepgzcW7e6jB+ps0qX8XqpBcnibAITg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T18:03:05Z"
  mac: ENC[AES256_GCM,data:2F7xNr0l2gUXXsez2VcKjaOq53isw2yS58HOl+jyeiu2prT5WB5A7pzguKTXWvmbspRHYGXBVziGEtvUhIpj2Xmgd/RA0+MpSeJnTU+meltN5AHRa0NuJIheZRix2uKA1fYBtfmQB++NixuSRA014Tkmq0zPMYuH4JZIIeggbkc=,iv:s81uQLQj//kIjo8YV5HY9O16GvrnAXya5hqJfIq5JMg=,tag:lUtrg3WyuTkiQLAAgwzjzg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
