{
 "title": "Sabnzbd",
 "description": "A dashboard for Sabnzbd. This plugin requires the use of https://github.com/msroest/sabnzbd_exporter. This dashboard is based off of the work of https://grafana.com/grafana/dashboards/9567 and updated for newer versions of grafana.",
 "tags": [
  "servers",
  "linux",
  "apps"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "download_server",
    "label": "Download server",
    "query": "label_values(sabnzbd_server_download_bytes, server)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sabnzbd_queue_download_rate_bytes_per_second"
    }
   ]
  },
  {
   "title": "Download time remaining",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sabnzbd_queue_remaining_seconds"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sabnzbd_queue_download_rate_bytes_per_second ",
     "legendFormat": "Speed"
    }
   ]
  },
  {
   "title": "Bytes remaining",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "sabnzbd_queue_remaining_bytes", "legendFormat": "Remaining" }
   ]
  },
  {
   "title": "Items in queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sabnzbd_queue_size " }
   ]
  },
  {
   "title": "Bytes remaining",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sabnzbd_queue_remaining_bytes" }
   ]
  },
  {
   "title": "Queue total size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sabnzbd_queue_total_size_bytes" }
   ]
  },
  {
   "title": "Downloaded",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sabnzbd_download_bytes{period = \"day\"}",
     "legendFormat": "Day"
    },
    {
     "expr": "sabnzbd_download_bytes{period = \"week\"}",
     "legendFormat": "Week"
    },
    {
     "expr": "sabnzbd_download_bytes{period = \"month\"}",
     "legendFormat": "Month"
    },
    {
     "expr": "sabnzbd_download_bytes{period = \"total\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sabnzbd_queue_size ", "legendFormat": "Remaining" }
   ]
  },
  {
   "title": "Queue remaining total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sabnzbd_queue_total_size_bytes ",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Download server: $download_server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "download_server"
  },
  {
   "title": "Day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sabnzbd_server_download_bytes{server=~\"$download_server\", period=\"day\"}",
     "legendFormat": "$download_server"
    }
   ]
  },
  {
   "title": "Week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sabnzbd_server_download_bytes{server=~\"$download_server\", period=\"week\"}"
    }
   ]
  },
  {
   "title": "Month",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sabnzbd_server_download_bytes{server=~\"$download_server\", period=\"month\"}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sabnzbd_server_download_bytes{server=~\"$download_server\", period=\"total\"}"
    }
   ]
  }
 ]
}