apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:6vpA+d4yx+HdP+7cYMAGG5YBpXEhXYWC2edxKJ5a6l3KFWXq3aV4bo5276hFNUMwwyyRl3ACswe7wYk3IfjEzRB4oEWHgbQ6sUc7YpsdD8gKbj5r5rkfP7PMzJo6J4cXvkimZJY219kRTYxolicmAAkz5z42QJc8VT/MtvURlnoCMce2fbXmIcF8gu8cWU3QdakpXH+KWNZ2smeFUKkvMAQCETvViEcHWdf/KzbtooMlGpgRgy7uhaQbyRU9t6UqHzEmdq0Q1mWDb5DQ/m5QpxAaRuI9zMz1+SnwLJpi/8HAYkYbNJHlbM/cdcUPqNEU,iv:OXbtcxhCdpSWVNalcimkh6QbccMyeeb7akemwrwIzDQ=,tag:mzLS0XB6/gMpfFIH89TiXw==,type:str]
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxS1k4b0lKWFlCbURoek10
        TU5rem5vbEtvR2gwck5NYmRGbHo0RTExaUhjCkxINlcvNENVbXhVdW5CYkpSWUFh
        UUhQZnV3eXR2SGtqcU5nRitHWXQ3Vk0KLS0tIGwydVVybnhXcTk4N25GeEZ2MnBq
        SzdieEdhTkJzQmZDSmg5N3U1VnpoalkKoucOV53Go2s3dtidCylQXOMWTuemlbar
        hEET2lotD2RqhCLgNqxYUKgyO1KTbWfUN0Map2jmpXJcRicOKZu5+w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-25T22:36:05Z"
  mac: ENC[AES256_GCM,data:74wHzGhSdqMFWGotUWQQhHvBhtSUHyLWu7QmQtgCi1KHg1+tz3o2Z5pvEnCcXc6bunZLp88/CCkt6daTFGv411essu8YQHsRHOJVUpUa3kScziHDyCbrwqtPA7hkyrqXiVDgqg7W6AAdcL5zOoPVU2842CGriWPFbe0e55BcEws=,iv:In/vdCE++7DobepRSHKNpCAxcGnfuYltTNiB34lulh8=,tag:EwO3o136l80mFSNuClITWA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
