apiVersion: v1
kind: Secret
metadata:
  name: volsync-restic-secret
type: Opaque
stringData:
  SECRET_VOLSYNC_S3_ENDPOINT: ENC[AES256_GCM,data:RUBIw3j+LkflKkTW6QyiihejR6PjC6qzm8C7ezHoMQ==,iv:OcgIZhFbTjvr5fU2v4157cwuS1MJxDdzXYchLwjsN/8=,tag:sGJaK/qenQsdkmN9qIp95g==,type:str]
  SECRET_VOLSYNC_S3_BUCKET: ENC[AES256_GCM,data:21lccj0Hfsdi/fmZYUUYjtsOd1L0aCV9WTGFzN7JBIgshxi/nA==,iv:IvHvzHq4IhcsM4lpheAH4p+nzMxO0ym19Ju9TN4bAfg=,tag:xcKUaMGTYQCdBCB4gDtpRg==,type:str]
  SECRET_VOLSYNC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:wtkq8uuYFHhyGJplbt/NawtLgEjOOMcKRA==,iv:7/WGt8ecFXfag9+1FvNGsuuItTfMBfNKQ4S20elWRag=,tag:qnDf1JxmpOGJmUuzMjRKqQ==,type:str]
  SECRET_VOLSYNC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zrQn463WHI1Nd69JeyF+s9LXHRcLsxeTAdTnmMoTOhxU+wjlguYCoA==,iv:xy7N2KAhSA2FNDL7JSbF8WIY5jJBiNf/TjG5ffc0QsM=,tag:v5vH/cOUSjQM2t2DUwhctQ==,type:str]
  SECRET_VOLSYNC_RESTIC_PASSWORD: ENC[AES256_GCM,data:XbmYzDwWRKIFxIZ9BsnR1NxMa8oE2Z3qMF5zxFgKa5i2IRHnkwkO1YmnNMiwrL7BKmp0tTB6JblCrODVgbahkg==,iv:lYUhhE7x++yvQrHzHK1Ae48p8KTgcdbjeaYHvPBqO3E=,tag:0a0HUJjTNG/7D0JTccoGZg==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMm55YkVhTit6MjJSQ0gx
        bEFJcHc1M0QrSGVUZElMMGJYZGhRUk55TVc0CjZOZndkOUwxNmtnVzNMUWtJblFs
        MmNpTVc2NFp1TU1KbWVXalpQcjZJSVEKLS0tIDZteFhUeGFmMXQ5VWZ6bmhOYWR2
        OS9wV1J4NW1NT2h5VjRqb00reEZCNjQK99nNHM1tSoGZbBzktrLjRPl0lJtPKx5L
        8qYVG592RgLeYjzdH35Swh/oCmshc0unRyE7XXFsy33+cptFpI/2rQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-21T10:19:59Z"
  mac: ENC[AES256_GCM,data:692lCsXlhJtBLLAS3Jtk4b6xQC3sHXA8C5pKm9cbzzRBr6tpvg6isLaxbbEC0hZPn51Sjqa9CX5tcmcrVm1Tu/RgQx1NtijcghMo92ErTZTFiX3jEw2XmrHGjHSYnCTJWDEdVZisVlxZv96pKtjCjN+M6fJqbi2e7vxirZpSum4=,iv:QfUyjbbDLlwUG728Nnk4k7Ga2yS/a7XnNmvIP6Geets=,tag:vz0MgL7TyMR5jP/xNPb1cQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
