apiVersion: v1
kind: Secret
metadata:
  name: radarr-importer
  namespace: default
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:b9yWqHmwbhXAqHfLOGF3WrHkMr5v5DRfJRwnclLkLmA=,iv:4iB9mNopZMbiS8zP+p3vxRWBfcTKcGc1j8WVcb6gT/s=,tag:h8lHyYFRM9OebvnzJTHsew==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:1wP+rKewaY5RGmRklnl+In9AVABNVz0mnT/LorW9Sja3805hNCJGn60MSm/4/Eo78c5YiMnPksr28T7S33j+zFFOlqaruVCDYs4Tp6gBCMRUruy43o2yaKgTwFsbYSbCEdzb2jxA9mTBY5xiv26Uv5lhlZH3Ftg1mMurjD+T35obqaDhFSaou/o0HKTVyWHFB9hHIi8pEk+3wkbz+O9q21O4oh4=,iv:SbSK5vQMR+8Hd388toQWAWadjv3O3PDKf7KGE+N/Evo=,tag:xMuZqDwp+iQTwbSRb+wcsQ==,type:str]
  TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:wbxbOqjosgwm1utp61Nezg8rhg+PyD0NoMDIwZLlPGcz02F6+JPFDjh/GEokpA==,iv:JXpt/Q8Puqyf/6ACAL2fWEiYqPLFt1gdPhiy9+Nwx8M=,tag:JDwh6B7Miy/zxod/7EtaSw==,type:str]
  WEBHOOK_TOKEN: ENC[AES256_GCM,data:MA5wcfI5nb9n2IRhE1R8ng==,iv:1dG8c+L5cI09asITj3xVKeXeOyLtds4Q8zRVIPNbf9A=,tag:i1JFpo45Lba0VzsOt/ARwQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MU5HOXNqN25XMDBiN1ZQ
        L3BLQXVjTWNiWm11dnBvRmZlNlN2U21TbXhFCk1oOTlVQmp0WmxhTXhVU05jYng1
        ZzNHVzVEZHc1R080VUdDUGhjNzRmZU0KLS0tIFBWNDZyVkR4NzMxS0tIclVnN1pt
        SCtNbGpmT1MxY1hNdmNMRlNCa25IY2cKGvayr6pWDYKhJWKEqN1x8GiTHPfeZWmS
        flAfiMlHCjkbccHGg4G7dw9g8c3xBfYZyQjzqVt2v/MBmcP/nBKinQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-25T22:51:03Z"
  mac: ENC[AES256_GCM,data:kfU6A/pbNjwBfFQnehX6owAitCdkX4cZgliZZrRq58mglJzpxIu3BUdmiYUAUdbUIU0vVVQZrHnvUhzNh+8YHfTFTneFucDRgTi8KH8sr9J+mthcSKwVrUNZ7kiAAiOLAJ5HSEdMiRrm+l+khCYrqrKkshksS85TL1UwHqiLbGE=,iv:0+90fO/AU0ctTAbifUM9NZ7olx+0L+wH264f11ooV90=,tag:MqA8Q3dT9qWhLKIE2RO9TA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
