---
apiVersion: v1
kind: ConfigMap
metadata:
  name: downloads-sftp-config
data:
  sftpgo.yaml: |
    sftpd:
      host_keys:
        - /host-keys/ssh_host_ed25519_key
      password_authentication: false
      keyboard_interactive_authentication: false
      enabled_ssh_commands: []
