apiVersion: v1
data:
  ssh_host_ed25519_key: ENC[AES256_GCM,data:t7bWSCFzUF0zfvk6I4S/kUhby+5VQrq5Q8LkKYeb+ot8YifRyitvjapoxw3ZIEfiXdbg2Q8cfOt9MfTOuPtZemT+jhZ3iYi5q7kbvMFv2+QByoSRlRPTn6AVZ3jp4xhjMa5OudkXBqNJi+rUdrzZmc3Uws9nUWEwIVVaXVaQAu79V+kOsREXMomdSoc4+71/IHZ9jg3S/M2McA/jDYg6YLc53LskV7+aAadkrgQMdcghVV8DGTAVY25d8fJxOTj8ZR/R0akbgz31trHk9ju+JM5B9X1dapY0p7JYeXSb4EbP22YU8AmYc0CEy7o2w+t6Ja+kaJRtsg4hwDt4nlmsp7vQztveED0YjYKHddHjbPysTdfo+J3jZW9cf7OFK4o17LfI/IHvSwz1OfngWOYaic7dEhZqwtxL3YPNFFMOYeN31JBfCTcUk+aDoDkX1u196lhyhlweK0kbKZgR+AtzrE3ULCZAfvG7OGuUNbAM4CGoY1oCPVZ9CqtbpWkyUq85jtm8Ni6/WkaUjIYkXKy4Qt+sjeU9Dmkb//PtOM4bERXxyTgsJbC1+5gOAIu/n+6qMQLMzlApsAhIrN+Dhpk/4+C3wKSXITuTIT6XJTzcyCTBbBz1e6Io2rTjc8o/ICA7ccrZq1O8c/1tWhBr0PuBIT38T1OcRoVbAwjMmNP+6QqAZZKuHr3ZYbOeQxtJgriPEGZJgO8GtLA2lLVfrKIZtSsjj+s=,iv:WhZHaf02STr3rpIAwbqcPliVWvhSifBgjxS1LctgE7w=,tag:1HHD0XDnCpy8oXMP2v2oRA==,type:str]
  ssh_host_ed25519_key.pub: ENC[AES256_GCM,data:j1QyWGjxM7C+0d8+Antx9Fcx6dc91MenL/FnlZlCZaHiVZ9LTWR+KYcbWfwWiFG6u9RnLRwv5OQ6yevwPWBNhpsbIGT4rpFYPBKib1ibt/1fR6vGLkbU7vcDtId0+ZQRYdufu298l9mrWgSse7LvgKUKHMEE2jSttKuYTtVM5RoOz+GXlIVFrg==,iv:71Hh+Y2kgvv+7YFoRamVfjs0do32kneuiUTetrCQlmE=,tag:fAJCtPHLJR10uiZUVUd5Vw==,type:str]
kind: Secret
metadata:
  name: downloads-sftp-host-key
  namespace: default
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UUR4UXg0N3o2VXduRWo4
        a1MvYlJzKzQwbWZwTmxSYlhqYnNEeHQ0ZEdRClA4ZDJBTVplcXlpUzFNN2w0OGdS
        MVRhY0Z4anRJUXk0K3pRMmhhQU9zZDgKLS0tIExmMFhVOWdIV09IbWVtbUxGUFoy
        VC9Nb3lqY3lWeTluUkFSTUNoV29Sam8K9kBGR0xxV3gH7TJXC/pmSWSNfZKvDfgc
        KR8T19BvxVPGuBu3/YDNzouGLoGH6RmHg75fXWBA/6MyJ4poZcuMnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T17:26:42Z"
  mac: ENC[AES256_GCM,data:J6utY0sIv20BDETjQIE1n86ZnoqT8bFkueKEqHAI/vEKd8Fo1YL9zkup79z1ng/dgZizZ9DYCE5Ghf6s591ENRK60LYPoeGq05tHyBSKxwQca/HjPZunZmzaWmky/qPyru4cB+f1AxwPo9xL3BCtHw2MFD5rsVi/a3UBXRKsneY=,iv:LcL6E344dNTJKFxxT7zw6cJSelYITam6q1TOS+Q6h7I=,tag:TDxzUpOI9g8RZNY2shgIHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
