---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./repository-secret.yaml
  - ./replicationsource.yaml
  - ./repository-secret-blobs.yaml
  - ./replicationsource-blobs.yaml
  - ./repository-secret-metadata.yaml
  - ./replicationsource-metadata.yaml
