---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: stash-metadata
spec:
  sourcePVC: stash-metadata
  trigger:
    schedule: "15 15 * * 1"
  restic:
    repository: stash-metadata-volsync-repo
    copyMethod: Direct
    cacheStorageClassName: openebs-hostpath
    cacheCapacity: 1Gi
    pruneIntervalDays: 7
    moverSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    retain:
      daily: 14
      weekly: 8
      monthly: 6
