---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: data-obsidian-livesync-0
spec:
  sourcePVC: data-obsidian-livesync-0
  trigger:
    schedule: "30 6 * * 1"
  restic:
    repository: obsidian-livesync-data-volsync-repo
    copyMethod: Direct
    cacheStorageClassName: openebs-hostpath
    cacheCapacity: 1Gi
    pruneIntervalDays: 7
    moverSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    retain:
      daily: 14
      weekly: 8
      monthly: 6
