apiVersion: v1
kind: Secret
metadata:
  name: loki-minio-credentials
type: Opaque
stringData:
  S3_ACCESS_KEY: ENC[AES256_GCM,data:t9wQz9R5+A==,iv:uKMaF4iVmCxKeIcPLrTDcUCe4GJcb+/A/xifstQAEkY=,tag:i9Z2fUWFM64JKG+obcdFAA==,type:str]
  S3_SECRET_KEY: ENC[AES256_GCM,data:I7wMeWjghLLcZVbhNNZNWA==,iv:9F1/AHWd8Y68r/YeZgYDLrgQBij2xYGb4m6ovdPgyM4=,tag:RaOF10P3uNlO4xAAZgtF/w==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcit5RjFJOW10WC9tUHRj
        RTJTemYwRDl1enRzcVFKbDFoWHllRFMzZlJNClkwK3VQUGFlNnl1NmxBQ2RrR1Bl
        c0dSNG1sa3Q0SDJsZ042cTAvcnorSWcKLS0tIGorZTkyQS81RFdOekt6Q1pOSjha
        eTZMdlVZS3RSU1F0SThjbnplT244RjAK2mOfvmNbqJR+1YVqHg8ufBugOoqp3st4
        S/2ehi0rRh4OV66NhfR04Lu+H5XQAzqRAU9HKNsOwvbD+NHQeL6b8Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T18:10:52Z"
  mac: ENC[AES256_GCM,data:KLltLTqKyYASwVI1XbnkJQjXqpbwZZ6bw1mUThPVZW8LQbfdB1eJQF52Z3WqykzovW/JRLWM73DCGnuzkGKEpvimXm5T635U2sgGIBZZpzhuaicqi9+L2eeJC1ilDDEhoDh0MaeXcI2NyFfHA6aIv5xGts/XvPHpqTAtS4CA3Oo=,iv:vFN/WF57p2wNBXJZdBkao+XzoyZ2VtxXrYc5iPq1wLE=,tag:eL+glwFW9CokIW8Y8r4RGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
