---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: volsync-rules
spec:
  groups:
    - name: volsync.rules
      rules:
        - alert: VolSyncReplicationOutOfSync
          expr: volsync_volume_out_of_sync{role="source"} > 0
          for: 30m
          labels:
            severity: critical
            component: backup
          annotations:
            summary: >-
              VolSync replication source {{ $labels.obj_namespace }}/{{ $labels.obj_name }} is out of sync
            description: >-
              VolSync reports that {{ $labels.obj_namespace }}/{{ $labels.obj_name }} is out of sync using {{ $labels.method }}.
        - alert: VolSyncMissedIntervals
          expr: increase(volsync_missed_intervals_total{role="source"}[8d]) > 0
          for: 5m
          labels:
            severity: warning
            component: backup
          annotations:
            summary: >-
              VolSync replication source {{ $labels.obj_namespace }}/{{ $labels.obj_name }} missed a scheduled run
            description: >-
              VolSync reports missed scheduled replication intervals for {{ $labels.obj_namespace }}/{{ $labels.obj_name }} in the last 8 days.
