apiVersion: v1
kind: Secret
metadata:
  name: minio-infra-env-configuration
type: Opaque
stringData:
  config.env: ENC[AES256_GCM,data:EI2/WcTm043kXtRZNCdnEN4XJdiG+VA427E7l0sKf55bAnntPvi3pykbhr96y2S0WC4XI1+FRmrPwQGTSIvFiwylvHbDBR/F/kcTrhgy,iv:2ktxMZ27zIBh2P0xXP9CXS9DK1/OK45PbDOj/mZK08U=,tag:5Lf0uJrmDYSSRH51QkHhxQ==,type:str]
sops:
  age:
    - recipient: age1kaeupmjdqc74w54956ryp02x4tfautx7yp8z22sh6jp30408jphqz5tdc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRisxbksyN3VRbFJZVUNY
        Zmd0VWFKUkYycWtZUzJsWnczZlhtemZwdlE0CkZpSUxITERKRjE3YXlqTXR6dVdZ
        TDZhUi9MZEdXSDRkQW1JdDg3dXVSUFkKLS0tIDZJeHE2VkxWcjN0elhXK25rNXFj
        Y21xeG1aM0tZa1hDODVjY2YyYklkazgKV98xK+AG3Xre0EvafQk5AnctX3+Hjm1d
        qjLXDEJxNH3/wcMwNQ2Y8NtePzV2nQ24obr6/yHwnDu2Uv/2dXgmxw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-24T18:10:40Z"
  mac: ENC[AES256_GCM,data:OZVCMg1/HCTnfgoMvd7NFrSABzcFEq37p9vwx0s+DJM4Srs0Lcre+nN2VEWF0Urknmq6ngNCT5ZjoCg9PjajLBiCtiDc6Nji06OMwd4DJ22Vnbn2PAvDXW/wu+7whL5tUVsaIjibPQdyd8E0YX2jjCXBjuSBveXGqycjqO/OAf0=,iv:4IT4V1DkMWwrR9Uar5ebYPn4k3Aqv54Hi9zqrLACqVU=,tag:kwdeL1OpoqVEsYou+HLFyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
